apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  initContainers:
  - image: busybox
    name: setup
    command:
    - "/bin/sh"
    - "-c"
    args:
    - "wget -O- google.com"
  containers:
  - image: nginx
    name: complex-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
