apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-exchange
  name: data-exchange
spec:
  containers:
  - image: busybox
    name: main-app
    command:
    - "/bin/sh"
    - "-c"
    args:
    - 'counter=1; while true; do touch "/var/app/data/$counter-data.txt"; counter=$((counter+1)); sleep 30; done'
    volumeMounts:
    - name: data-dir
      mountPath:  /var/app/data
    resources: {}
  - image: busybox
    name: sidecar
    command:
    - "/bin/sh"
    - "-c"
    args:
    - "while true; do sleep 60; ls /var/app/data/* | wc -l; done"
    volumeMounts:
    - name: data-dir
      mountPath:  /var/app/data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: data-dir
    emptyDir: {}
status: {}
