apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
spec:
  containers:
  - image: nginx
    name: consumer
    ports:
    - containerPort: 80
    env:
    - name: API_KEY
      valueFrom:
        configMapKeyRef:
          name: ext-service-configmap
          key: api_endpoint
    - name: USER_NAME
      valueFrom:
        configMapKeyRef:
          name: ext-service-configmap
          key: username
    volumeMounts:
    - name: ext-service-secret
      mountPath: "/var/app"
      readOnly: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: ext-service-secret
    secret:
      secretName: ext-service-secret
status: {}
