apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loop
  name: loop
  namespace: ckad
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do date; sleep 10; done
    image: busybox
    name: loop
    env:
    - name: "UI_PROP_FILE_NAME"
      valueFrom:
        configMapKeyRef:
          name: game-demo
          key: ui_properties_file_name 
    volumeMounts:
    - name: config
      mountPath: "/config"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: config
    configMap:
      name: game-demo
      items:
      - key: "user-interface.properties"
        path: "user-interface.properties"
status: {}
