apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: ckad
spec:
  containers:
  - image: nginx:1.17.10
    name: nginx
    env:
    - name: DB_URL
      value: postgresql://mydb:5432
    - name: DB_USER
      value: admin
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
